version: 2

jobs:
  test:
    machine: true
    steps:
      - checkout

      - run: .circleci/run_compose.sh up -d && sleep 10

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: .circleci/run_compose.sh run nodejs npm ci
      - run: .circleci/run_compose.sh run -e RABBIT_URI=amqp://rabbit nodejs npm run ci-test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: .circleci/run_compose.sh down

      - store_test_results:
          path: test-results

      - persist_to_workspace:
          root: ~/repo
          paths: .

  sanity:
    machine: true

    steps:
      - checkout

      - run:
          command: cd sanity && ../.circleci/run_compose.sh up -d && sleep 20

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-sanity-dependencies-{{ checksum "sanity/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-sanity-dependencies-

      - run:
          command: ../.circleci/run_compose.sh run nodejs npm ci
          working_directory: sanity
      - run:
          command: .circleci/run_compose.sh run -e RABBIT_URI=amqp://rabbit nodejs npm run ci-test
          working_directory: sanity

      - save_cache:
          paths:
            - sanity/node_modules
          key: v1-sanity-dependencies-{{ checksum "sanity/package.json" }}

      - run: .circleci/run_compose.sh down

      - store_test_results:
          path: test-results

  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  ticktok-npm:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - sanity:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - sanity
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
